{
  "comments": [
    {
      "key": {
        "uuid": "14416311_4161f37d",
        "filename": "dlrn/tests/test_shell.py",
        "patchSetId": 1
      },
      "lineNbr": 565,
      "author": {
        "id": 535
      },
      "writtenOn": "2021-02-25T13:23:39Z",
      "side": 1,
      "message": "Would it be worthwhile/possible having a test with the same commit timestamp but a different distgit one, if that is what caused the issue with the last patch?",
      "revId": "be3b53ce655f269930590a224a67428890602f51",
      "serverId": "6c1dc8ef-8b94-40e4-bd83-c2359d45ecc0",
      "unresolved": false
    }
  ]
}